image: selu383envoc/383build

pipelines:
  default:
    - step:
        name: "Build/Test"
        script:
          - dotnet test FA20.P01.Tests.Web
        services:
          - docker
  branches:
    master:
      - step:
          name: "Build/Test/Publish"
          script:
            - dotnet test FA20.P01.Tests.Web
          services:
            - docker
          artifacts:
            - publish/*.zip

definitions:
  services:
    docker:
      memory: 2048